### ISSUE TITLE
"Download all CVs" button does not work

### ISSUE THREAD

**Issue by agentmilindu** [UCSC-LK/CV-APP-2017#23]
"Download all CVs" button does not work but the "PDF" button does the job.

![image](https://user-images.githubusercontent.com/1391468/30652935-4ba3c7ac-9e47-11e7-8d1b-436bef7af20f.png)

Am I mistaken? If not, I think we can remove the  "Download all CVs" button and rename "PDF" button as "Download all CVs" button, right?

**Comment by vihanga-liyanage** [comment]
This could happen if there is a popup block. Check whether that's the case. PDF button gives a pdf of that table but Download all CVs button is supposed to send a zip of CVs of all candidates in the table.

**Comment by agentmilindu** [comment]
Gotcha. Why a Popup for  'Download all CVs'? That's confusing, Chrome does not give a proper warning even, only a small icon in the address bar. If it has to be a popup, shall we show a small tip kinda something. What do you think?

**Comment by vihanga-liyanage** [comment]
Currently we've used a window.open() to download the zip file. Anything better than that would do. :)
